name: php-unit

on:
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Composer Downloads
        uses: actions/cache@v2
        with:
          path: vendor/
          key: ${{ runner.OS }}-composer-${{ hashFiles('**/composer.lock') }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Installing dependencies (/◕ヮ◕)/ ....
        run: composer install --ignore-platform-reqs --optimize-autoloader

      - name: Dumping autoload (/◕ヮ◕)/ ....
        run: composer dumpautoload -o

      - name: Start php unit ¯\_(ツ)_/¯ ....
        run: ./vendor/bin/phpunit ./tests
